# Generated by Django 3.0.5 on 2022-08-10 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weburl_text', models.CharField(max_length=300)),
                ('pub_date', models.DateTimeField(verbose_name='date added')),
            ],
        ),
    ]
