# Generated by Django 2.1.5 on 2022-08-22 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('go', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordUnknown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng_word', models.CharField(max_length=300)),
                ('chi_word', models.CharField(max_length=500)),
                ('tag', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='weburl',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
